Repository ansible/schemas, pull requests merged in 2021-04, with the labels that each got.

#24 Improve zuul schema
  examples/zuul.d/jobs.yaml
  f/zuul.json
  src/ansibleschemas/zuul.py
Labels: bug

#25 Add dependency locking
  requirements.txt
  src/ansibleschemas/_modules.py
  tox.ini
Labels: enhancement

#26 Warn contributors to not edit generated files
  f/README.md
Labels: enhancement

#27 Add vars argument to role dependencies
  f/ansible-meta.json
  src/ansibleschemas/_galaxy.py
  src/ansibleschemas/meta.py
  tox.ini
Labels: enhancement

#29 Add optional `issue_tracker_url` key
  src/ansibleschemas/meta.py
Labels: enhancement

#28 Add job attempts to zuul
  examples/zuul.d/jobs.yaml
  f/zuul.json
  src/ansibleschemas/zuul.py
Labels: bug

#31 Fixed missing bigsur
  .gitignore
  f/ansible-meta.json
  pyproject.toml
Labels: bug

#32 Add support for vars_prompt
  examples/playbooks/run.yml
  f/ansible-playbook.json
  src/ansibleschemas/playbook.py
Labels: enhancement

#34 Create CODEOWNERS
  .github/CODEOWNERS
Labels: skip-changelog

#35 Create FUNDING.yml
  .github/FUNDING.yml
Labels: skip-changelog

#36 Add ability to recognize files with encrypted vaults
  examples/playbooks/vars/encrypted.yml
  examples/playbooks/vars/myvars.yml
  f/ansible-meta.json
  f/ansible-playbook.json
  f/ansible-vars.json
  src/ansibleschemas/vars.py
  tox.ini
Labels: enhancement

#39 Implement testing using mocha
  .github/workflows/test.yml
  .mocharc.json
  examples/reqs3/meta/requirements.yml.fail
  f/ansible-galaxy.json
  f/ansible-lint.json
  f/ansible-meta.json
  f/ansible-playbook.json
  f/ansible-requirements.json
  f/ansible-tasks.json
  f/ansible-vars.json
  f/molecule.json
  f/zuul.json
  package-lock.json
  package.json
  src/ansibleschemas/ansiblelint.py
  src/ansibleschemas/galaxy.py
  src/ansibleschemas/meta.py
  src/ansibleschemas/molecule.py
  src/ansibleschemas/playbook.py
  src/ansibleschemas/requirements.py
  src/ansibleschemas/tasks.py
  src/ansibleschemas/vars.py
  src/ansibleschemas/zuul.py
  src/schema.spec.ts
  tsconfig.json
Labels: enhancement
