Repository ansible/schemas, pull requests merged in 2021-05, with the labels that each got.

#50 Add new property for MoleculePlatformModel
  f/molecule.json
  src/ansibleschemas/molecule.py
Labels: bug

#41 Export all ansible community modules
  .pre-commit-config.yaml
  f/ansible-playbook.json
  f/ansible-tasks.json
  src/ansibleschemas/tasks.py
  src/schema.spec.ts
  tox.ini
  words.txt
Labels: enhancement

#52 Add development config
  .vscode/extensions.json
  .vscode/settings.json
Labels: skip-changelog

#51 Upgrade dependencies
  package-lock.json
  package.json
  tox.ini
Labels: skip-changelog

#54 Update dependencies
  f/ansible-playbook.json
  f/ansible-tasks.json
  package-lock.json
  package.json
  requirements.txt
  src/ansibleschemas/_modules.py
  tox.ini
Labels: enhancement

#57 Add validation of playbooks for ProvisionerModel
  examples/molecule/default/molecule.yml
  f/ansible-galaxy.json
  f/molecule.json
  src/ansibleschemas/_modules.py
  src/ansibleschemas/molecule.py
Labels: bug

#59 Extend validation schema for molecule's platform
  f/ansible-playbook.json
  f/ansible-tasks.json
  f/molecule.json
  src/ansibleschemas/_modules.py
  src/ansibleschemas/molecule.py
Labels: enhancement

#60 Extend config file example for molecule's platform
  examples/molecule/default/molecule.yml
  f/molecule.json
  src/ansibleschemas/molecule.py
Labels: enhancement
