Repository ansible/schemas, pull requests merged in 2021-12, with the labels that each got.

#94 add missing property `pre_build_image` to MoleculePlatformModel
  examples/molecule/default/molecule.yml
  f/molecule.json
  src/ansibleschemas/molecule.py
Labels: bug

#98 make `scenario` optional for molecule
  f/molecule.json
  src/ansibleschemas/molecule.py
Labels: bug

#99 update dev dependency mocha to ^9.0.0 because of CVE-2021-3807 in ansi-regex
  package-lock.json
  package.json
Labels: bug

#96 use `all` instead of `any` for PlatformVersionsEnum
  examples/roles/foo/meta/main.yml
  f/ansible-meta.json
  src/ansibleschemas/meta.py
Labels: bug

#97 make `company` optional for ansible-meta as galaxy source suggests
  f/ansible-meta.json
  src/ansibleschemas/meta.py
Labels: bug

#100 add optional `name` for scenario in molecule schema
  examples/molecule/cluster/molecule.yml
  examples/molecule/default/molecule.yml
  f/molecule.json
  src/ansibleschemas/__main__.py
  src/ansibleschemas/molecule.py
Labels: bug

#101 Bump linters
  .pre-commit-config.yaml
  conftest.py
  src/ansibleschemas/galaxy.py
  src/ansibleschemas/tasks.py
Labels: skip-changelog

#102 update GALAXY_PLATFORMS dumped from API
  f/ansible-meta.json
  src/ansibleschemas/_galaxy.py
Labels: bug

#104 make dumping galaxy platforms configurable and update documentation
  CONTRIBUTING.md
  README.md
  src/ansibleschemas/__main__.py
  tox.ini
Labels: enhancement

#95 update GALAXY_PLATFORMS dictionary
  f/ansible-meta.json
  src/ansibleschemas/_galaxy.py
Labels: enhancement

#108 fix typos in schema comment
  src/ansibleschemas/ansiblelint.py
  src/ansibleschemas/galaxy.py
  src/ansibleschemas/meta.py
  src/ansibleschemas/molecule.py
  src/ansibleschemas/playbook.py
  src/ansibleschemas/requirements.py
  src/ansibleschemas/tasks.py
  src/ansibleschemas/vars.py
  src/ansibleschemas/zuul.py
Labels: bug

#111 Bumped project dependencies
  package-lock.json
  package.json
  requirements.txt
  tox.ini
Labels: skip-changelog

#112 Rename requirements.txt to constraints.txt
  .github/workflows/dump.yml
  CONTRIBUTING.md
  constraints.txt
  tox.ini
Labels: skip-changelog

#113 Refreshed ansible module dumps to 5.0.1
  data/modules-meta.json
  data/modules-name.json
  f/ansible-playbook.json
  f/ansible-tasks.json
Labels: enhancement

#117 Remove module dumping
  .github/workflows/dump.yml
  .github/workflows/test.yml
  data/modules-meta.json
  data/modules-name.json
  setup.cfg
  src/ansibleschemas/__main__.py
  src/ansibleschemas/tasks.py
  tox.ini
Labels: enhancement

#118 Remove modules from schemas
  f/ansible-playbook.json
  f/ansible-tasks.json
  tox.ini
Labels: enhancement

#122 vscode setting black
  .vscode/settings.json
  README.md
Labels: skip-changelog

#116 update and not overwrite the existing list of galaxy platforms
  src/ansibleschemas/__main__.py
  src/ansibleschemas/_galaxy.py
Labels: enhancement

#124 Fix CODEOWNERS file
  .github/CODEOWNERS
Labels: skip-changelog

#121 log ajv validation errors to console
  src/schema.spec.ts
Labels: bug

#120 remove doc8 pre_commit task
  .pre-commit-config.yaml
Labels: skip-changelog
