Repository ansible/schemas, pull requests merged in 2022-06, with the labels that each got.

#297 Add missing write_list in ansible-lint schema
  f/ansible-lint.json
  negative_test/.config/ansible-lint.yml
  test/.config/ansible-lint.yml
Labels: bug

#299 Added openwrt to meta schema
  f/ansible-meta.json
Labels: bug

#303 Update test dependencies
  package-lock.json
  package.json
  tox.ini
Labels: skip-changelog

#304 Add missing test file
  negative_test/.config/ansible-lint.yml.md
Labels: skip-changelog

#305 Allow tags with import_playbooks
  f/ansible-playbook.json
  f/ansible-tasks.json
  f/ansible.json
  test/playbooks/import_playbook.yml
Labels: bug

#306 Allow use of when with meta/main.yml
  f/ansible-meta.json
  negative_test/roles/role_with_bad_deps_in_meta/meta/main.yml.md
  test/roles/maximum/meta/main.yml
Labels: bug

#307 Allow use of templates for integers
  f/ansible-playbook.json
  f/ansible-tasks.json
  f/ansible.json
  test/playbooks/integers.yml
Labels: bug

#311 Replace tox with taskfile as build tool
  .config/dictionary.txt
  .github/workflows/task.yml
  .gitignore
  Taskfile.yml
  package.json
  tox.ini
Labels: skip-changelog

#317 Add OpenWRTPlatformModel to items of platforms
  f/ansible-meta.json
Labels: bug

#318 Fix use of until keyword in schema
  f/ansible-playbook.json
  f/ansible-tasks.json
  f/ansible.json
  test/playbooks/tasks/until.yml
Labels: bug

#325 Make check-jsonschema output more verbose in tests
  negative_test/playbooks/environment.yml.md
  negative_test/playbooks/failed_when.yml.md
  negative_test/playbooks/ignore_errors.yml.md
  negative_test/playbooks/import_playbook.yml.md
  negative_test/playbooks/import_playbook_exclusive.yml.md
  negative_test/playbooks/invalid-failed-when.yml.md
  negative_test/playbooks/invalid-serial.yml.md
  negative_test/playbooks/invalid.yml.md
  negative_test/playbooks/invalid_become.yml.md
  negative_test/playbooks/local_action.yml.md
  negative_test/playbooks/loop.yml.md
  negative_test/playbooks/loop2.yml.md
  negative_test/playbooks/no_log_partial_template.yml.md
  negative_test/playbooks/no_log_string.yml.md
  negative_test/playbooks/roles.yml.md
  negative_test/playbooks/run_once_list.yml.md
  negative_test/playbooks/tags-mapping.yml.md
  negative_test/playbooks/tags-number.yml.md
  negative_test/playbooks/tasks.yml.md
  negative_test/playbooks/tasks/args_integer.yml.md
  negative_test/playbooks/tasks/args_string.yml.md
  negative_test/playbooks/tasks/become_method_untemplated.yml.md
  negative_test/playbooks/tasks/ignore_errors.yml.md
  negative_test/playbooks/tasks/invalid_block.yml.md
  negative_test/playbooks/tasks/local_action.yml.md
  negative_test/playbooks/tasks/loop.yml.md
  negative_test/playbooks/tasks/loop2.yml.md
  negative_test/playbooks/tasks/no_log_number.yml.md
  negative_test/playbooks/tasks/no_log_string.yml.md
  negative_test/playbooks/tasks/tags-mapping.yml.md
  negative_test/playbooks/tasks/tags-string.yml.md
  negative_test/playbooks/tasks/when_integer.yml.md
  negative_test/playbooks/tasks/when_object.yml.md
  negative_test/playbooks/tasks/with_items_boolean.yml.md
  negative_test/playbooks/tasks/with_items_untemplated_string.yml.md
  negative_test/playbooks/vars/asterisk.yml.md
  negative_test/playbooks/vars/dash-in-var-name.yml.md
  negative_test/playbooks/vars/list.yml.md
  negative_test/playbooks/vars/numeric-var-name.yml.md
  negative_test/playbooks/vars/play-keyword.yml.md
  negative_test/playbooks/vars/python-keyword.yml.md
  negative_test/playbooks/vars/varname-numeric-prefix.yml.md
  negative_test/playbooks/vas_prompt.yml.md
  negative_test/playbooks/with_cartesian.yml.md
  negative_test/playbooks/with_filetree.yml.md
  negative_test/playbooks/with_flattened.yml.md
  negative_test/reqs3/meta/requirements.yml.md
  negative_test/roles/meta/main.yml.md
  negative_test/roles/meta_invalid_collection/meta/main.yml.md
  negative_test/roles/meta_invalid_collections/meta/main.yml.md
  negative_test/roles/meta_invalid_role_namespace/meta/main.yml.md
  negative_test/roles/role_with_bad_deps_in_meta/meta/main.yml.md
  src/schema.spec.ts
Labels: skip-changelog

#326 Improve gather facts and subset support
  .config/dictionary.txt
  f/ansible-playbook.json
  f/ansible.json
  negative_test/playbooks/gather_facts.yml
  negative_test/playbooks/gather_facts.yml.md
  negative_test/playbooks/gather_subset.yml
  negative_test/playbooks/gather_subset.yml.md
  negative_test/playbooks/gather_subset2.yml
  negative_test/playbooks/gather_subset2.yml.md
  negative_test/playbooks/gather_subset3.yml
  negative_test/playbooks/gather_subset3.yml.md
  negative_test/playbooks/gather_subset4.yml
  negative_test/playbooks/gather_subset4.yml.md
  test/playbooks/gather_facts.yml
  test/playbooks/gather_subset.yml
Labels: enhancement

#327 Allow when inside import_playbook
  f/ansible-playbook.json
  f/ansible.json
  negative_test/playbooks/environment.yml.md
  negative_test/playbooks/failed_when.yml.md
  negative_test/playbooks/gather_facts.yml.md
  negative_test/playbooks/gather_subset.yml.md
  negative_test/playbooks/gather_subset2.yml.md
  negative_test/playbooks/gather_subset3.yml.md
  negative_test/playbooks/gather_subset4.yml.md
  negative_test/playbooks/ignore_errors.yml.md
  negative_test/playbooks/invalid-failed-when.yml.md
  negative_test/playbooks/invalid-serial.yml.md
  negative_test/playbooks/invalid.yml.md
  negative_test/playbooks/invalid_become.yml.md
  negative_test/playbooks/local_action.yml.md
  negative_test/playbooks/loop.yml.md
  negative_test/playbooks/loop2.yml.md
  negative_test/playbooks/no_log_partial_template.yml.md
  negative_test/playbooks/no_log_string.yml.md
  negative_test/playbooks/roles.yml.md
  negative_test/playbooks/run_once_list.yml.md
  negative_test/playbooks/tags-mapping.yml.md
  negative_test/playbooks/tags-number.yml.md
  negative_test/playbooks/tasks.yml.md
  negative_test/playbooks/vas_prompt.yml.md
  negative_test/playbooks/with_cartesian.yml.md
  negative_test/playbooks/with_filetree.yml.md
  negative_test/playbooks/with_flattened.yml.md
  test/playbooks/import_playbook.yml
Labels: bug
