Repository ansible/schemas, pull requests merged in 2022-07, with the labels that each got.

#332 chore: improve taskfile
  .config/dictionary.txt
  .config/requirements.in
  .config/requirements.txt
  .envrc
  .github/dependabot.yml
  .gitignore
  CONTRIBUTING.md
  Taskfile.yml
  requirements.in
  requirements.txt
  tools/test-setup.sh
Labels: skip-changelog

#345 Add Oracle Linux schema
  f/ansible-meta.json
Labels: bug

#347 Improve documentation on galaxy version pattern
  f/ansible-galaxy.json
Labels: enhancement

#348 Allow serial to use jinja2
  f/ansible-playbook.json
  f/ansible.json
  test/playbooks/run.yml
Labels: bug

#349 Allow role parameters on meta
  Taskfile.yml
  f/ansible-meta.json
  test/roles/meta-tags/meta/main.yml
Labels: bug
