Repository ansible/schemas, pull requests merged in 2022-09, with the labels that each got.

#363 Remove ansible-lint config schema
  f/ansible-lint.json
  negative_test/.config/ansible-lint.yml
  negative_test/.config/ansible-lint.yml.md
  test/.config/ansible-lint.yml
Labels: bug

#372 Fixed undefined var bug in test-setup.sh
  tools/test-setup.sh
Labels: skip-changelog

#370 Fix task and playbook detection in schema
  f/ansible-playbook.json
  f/ansible-tasks.json
  f/ansible.json
Labels: bug

#373 Add missing values for gather_subset
  .config/dictionary.txt
  f/ansible-playbook.json
  f/ansible.json
Labels: bug

#374 Enable auto-update of github-actions
  .github/dependabot.yml
Labels: skip-changelog

#378 Ensure test fails if git reports dirty
  Taskfile.yml
Labels: skip-changelog

#358 Improve molecule schema
  .config/dictionary.txt
  f/molecule.json
Labels: enhancement

#380 Improve contributing documentation
  CONTRIBUTING.md
Labels: enhancement

#381 Fix collection, role and namespace naming patterns
  f/ansible-galaxy.json
  f/ansible-meta.json
Labels: bug

#383 meta: ensure galaxy_info.author field is a valid github username
  f/ansible-meta.json
  negative_test/roles/v1_meta_author/meta/main.yml
  negative_test/roles/v1_meta_author/meta/main.yml.md
  test/roles/v1_role/meta/main.yml
Labels: bug

#384 meta: split into v1/v2 sub-schemas
  .config/dictionary.txt
  f/ansible-meta.json
  negative_test/roles/meta/main.yml.md
  negative_test/roles/meta_invalid_collection/meta/main.yml.md
  negative_test/roles/meta_invalid_collections/meta/main.yml.md
  negative_test/roles/meta_invalid_role_namespace/meta/main.yml.md
  negative_test/roles/role_with_bad_deps_in_meta/meta/main.yml.md
  negative_test/roles/v1_meta_author/meta/main.yml
  negative_test/roles/v1_meta_author/meta/main.yml.md
  test/roles/foo/meta/main.yml
  test/roles/maximum/meta/main.yml
  test/roles/meta-tags/meta/main.yml
  test/roles/ns/meta/main.yml
  test/roles/v1_role/meta/main.yml
  test/tests/integration/rom_role/meta/main.yml
Labels: enhancement

#385 meta: refactor schema versioning to improve errors
  Taskfile.yml
  f/ansible-meta.json
  negative_test/roles/empty_meta/meta/main.yml
  negative_test/roles/empty_meta/meta/main.yml.md
  negative_test/roles/meta/main.yml
  negative_test/roles/meta/main.yml.md
  negative_test/roles/meta_invalid_collection/meta/main.yml
  negative_test/roles/meta_invalid_collection/meta/main.yml.md
  negative_test/roles/meta_invalid_collections/meta/main.yml
  negative_test/roles/meta_invalid_collections/meta/main.yml.md
  negative_test/roles/meta_invalid_role_namespace/meta/main.yml
  negative_test/roles/meta_invalid_role_namespace/meta/main.yml.md
  negative_test/roles/role_with_bad_deps_in_meta/meta/main.yml
  negative_test/roles/role_with_bad_deps_in_meta/meta/main.yml.md
  test/roles/empty-meta/meta/main.yml
Labels: bug

#387 Replace meta version with galaxy_info.standalone
  f/ansible-meta.json
  negative_test/roles/empty_meta/meta/main.yml.md
  negative_test/roles/meta/main.yml.md
  negative_test/roles/meta_invalid_collection/meta/main.yml.md
  negative_test/roles/meta_invalid_collections/meta/main.yml.md
  negative_test/roles/meta_invalid_role_namespace/meta/main.yml.md
  negative_test/roles/role_with_bad_deps_in_meta/meta/main.yml.md
  test/roles/foo/meta/main.yml
  test/roles/maximum/meta/main.yml
  test/roles/meta-tags/meta/main.yml
  test/roles/ns/meta/main.yml
  test/roles/v1_role/meta/main.yml
  test/tests/integration/rom_role/meta/main.yml
Labels: bug

#389 meta: make the standalone field optional
  f/ansible-meta.json
  negative_test/roles/meta/main.yml
  negative_test/roles/meta/main.yml.md
  negative_test/roles/meta_invalid_collection/meta/main.yml
  negative_test/roles/meta_invalid_collection/meta/main.yml.md
  negative_test/roles/meta_invalid_collections/meta/main.yml
  negative_test/roles/meta_invalid_collections/meta/main.yml.md
  negative_test/roles/meta_invalid_role_namespace/meta/main.yml
  negative_test/roles/meta_invalid_role_namespace/meta/main.yml.md
  negative_test/roles/role_with_bad_deps_in_meta/meta/main.yml
  negative_test/roles/role_with_bad_deps_in_meta/meta/main.yml.md
  test/roles/foo/meta/main.yml
  test/roles/maximum/meta/main.yml
  test/roles/meta-tags/meta/main.yml
  test/roles/ns/meta/main.yml
  test/roles/v1_role/meta/main.yml
Labels: bug

#391 Remove user property from tasks, roles and block
  Taskfile.yml
  f/ansible-playbook.json
  f/ansible-tasks.json
  f/ansible.json
  test/playbooks/user_valid.yml
Labels: bug

#393 Support for cgroupns parameter
  .config/dictionary.txt
  f/molecule.json
Labels: bug

#394 meta: ensure standalone is optional
  f/ansible-meta.json
  negative_test/roles/meta/main.yml.md
  negative_test/roles/meta_invalid_role_namespace/meta/main.yml.md
  negative_test/roles/role_with_bad_deps_in_meta/meta/main.yml.md
  test/roles/foo/meta/main.yml
Labels: bug

#395 meta: allow empty meta schema files
  f/ansible-meta.json
  negative_test/roles/empty_meta/meta/main.yml
  negative_test/roles/empty_meta/meta/main.yml.md
  test/roles/empty-meta/meta/main.yml
Labels: bug

#398 Recognize listen keyword for handlers
  f/ansible-playbook.json
  f/ansible-tasks.json
  f/ansible.json
  test/playbooks/run.yml
Labels: bug

#396 Update molecule schema for vagrant
  .config/dictionary.txt
  f/molecule.json
  test/molecule/vagrant/molecule.yml
Labels: bug

#402 playbook: allow unsafe for vars_prompt
  f/ansible-playbook.json
  f/ansible.json
  test/playbooks/vars_prompt.yml
Labels: bug

#403 Make repository property required for galaxy
  f/ansible-galaxy.json
  test/galaxy.yml
Labels: bug

#404 var_files should accept null, array[string] and string
  f/ansible-playbook.json
  f/ansible.json
  negative_test/playbooks/var_files_list_number.yml
  negative_test/playbooks/var_files_list_number.yml.md
  negative_test/playbooks/var_files_number.yml
  negative_test/playbooks/var_files_number.yml.md
  test/playbooks/var_files.yml
Labels: bug
