Repository ansible/schemas, pull requests merged in 2022-05, with the labels that each got.

#246 vars: check valid names
  .config/dictionary.txt
  .pre-commit-config.yaml
  f/ansible-galaxy.json
  f/ansible-vars.json
  negative_test/playbooks/vars/asterisk.yml
  negative_test/playbooks/vars/dash-in-var-name.yml
  negative_test/playbooks/vars/numeric-var-name.yml
  negative_test/playbooks/vars/play-keyword.yml
  negative_test/playbooks/vars/python-keyword.yml
  negative_test/playbooks/vars/varname-numeric-prefix.yml
  src/update-schemas.py
  test/playbooks/vars/myvars.yml
Labels: enhancement

#247 meta: allow empty files
  f/ansible-meta.json
  test/roles/empty-meta/meta/main.yml
Labels: bug

#248 Dump errors to markdown
  negative_test/molecule/platforms_children/molecule.yml.md
  negative_test/molecule/platforms_networks/molecule.yml.md
  negative_test/playbooks/vars/asterisk.yml.md
  negative_test/playbooks/vars/dash-in-var-name.yml.md
  negative_test/playbooks/vars/list.yml.md
  negative_test/playbooks/vars/numeric-var-name.yml.md
  negative_test/playbooks/vars/play-keyword.yml.md
  negative_test/playbooks/vars/python-keyword.yml.md
  negative_test/playbooks/vars/varname-numeric-prefix.yml.md
  negative_test/reqs3/meta/requirements.yml.md
  negative_test/roles/meta/main.yml.md
  negative_test/roles/meta_invalid_collection/meta/main.yml.md
  negative_test/roles/meta_invalid_collections/meta/main.yml.md
  negative_test/roles/role_with_bad_deps_in_meta/meta/main.yml.md
  package-lock.json
  package.json
  src/schema.spec.ts
Labels: skip-changelog

#251 vars: correct keyword detection regex
  f/ansible-vars.json
  src/update-schemas.py
  test/playbooks/defaults/foo.yml
  test/playbooks/vars/myvars.yml
Labels: bug

#249 Add output from python check-jsonschema
  .config/dictionary.txt
  .pre-commit-config.yaml
  negative_test/molecule/platforms_children/molecule.yml.md
  negative_test/molecule/platforms_networks/molecule.yml.md
  negative_test/playbooks/vars/asterisk.yml.md
  negative_test/playbooks/vars/dash-in-var-name.yml.md
  negative_test/playbooks/vars/list.yml.md
  negative_test/playbooks/vars/numeric-var-name.yml.md
  negative_test/playbooks/vars/play-keyword.yml.md
  negative_test/playbooks/vars/python-keyword.yml.md
  negative_test/playbooks/vars/varname-numeric-prefix.yml.md
  negative_test/reqs3/meta/requirements.yml.md
  negative_test/roles/meta/main.yml.md
  negative_test/roles/meta_invalid_collection/meta/main.yml.md
  negative_test/roles/meta_invalid_collections/meta/main.yml.md
  negative_test/roles/role_with_bad_deps_in_meta/meta/main.yml.md
  package-lock.json
  package.json
  requirements.txt
  src/schema.spec.ts
Labels: skip-changelog

#253 Synched md files
  negative_test/playbooks/vars/asterisk.yml.md
  negative_test/playbooks/vars/dash-in-var-name.yml.md
  negative_test/playbooks/vars/numeric-var-name.yml.md
  negative_test/playbooks/vars/play-keyword.yml.md
  negative_test/playbooks/vars/python-keyword.yml.md
  negative_test/playbooks/vars/varname-numeric-prefix.yml.md
Labels: skip-changelog

#254 Update deps
  package-lock.json
  package.json
Labels: skip-changelog

#256 meta: allow tags to use a single string
  f/ansible-meta.json
  test/roles/meta-tags/meta/main.yml
Labels: bug

#257 Improve inventory schema
  f/ansible-inventory.json
  negative_test/inventory/broken_dev_inventory.yml
  negative_test/inventory/broken_dev_inventory.yml.md
  test/inventory/inventory.yml
  test/inventory/production.yml
Labels: bug

#260 Compile tasks and playbooks subschemas
  .pre-commit-config.yaml
  f/ansible-playbook.json
  f/ansible-tasks.json
  negative_test/playbooks/ignore_errors.yml.md
  negative_test/playbooks/import_playbook.yml.md
  negative_test/playbooks/invalid-failed-when.yml.md
  negative_test/playbooks/invalid-serial.yml.md
  negative_test/playbooks/invalid.yml.md
  negative_test/playbooks/local_action.yml.md
  negative_test/playbooks/loop.yml.md
  negative_test/playbooks/loop2.yml.md
  negative_test/playbooks/no_log_partial_template.yml.md
  negative_test/playbooks/no_log_string.yml.md
  negative_test/playbooks/roles.yml.md
  negative_test/playbooks/tags-mapping.yml.md
  negative_test/playbooks/tags-number.yml.md
  negative_test/playbooks/tasks.yml.md
  negative_test/playbooks/tasks/become_method_untemplated.yml.md
  negative_test/playbooks/tasks/ignore_errors.yml.md
  negative_test/playbooks/tasks/invalid_block.yml.md
  negative_test/playbooks/tasks/local_action.yml.md
  negative_test/playbooks/tasks/loop.yml.md
  negative_test/playbooks/tasks/loop2.yml.md
  negative_test/playbooks/tasks/no_log_number.yml.md
  negative_test/playbooks/tasks/no_log_string.yml.md
  negative_test/playbooks/tasks/tags-mapping.yml.md
  negative_test/playbooks/tasks/tags-string.yml.md
  negative_test/playbooks/tasks/with_items_boolean.yml.md
  negative_test/playbooks/tasks/with_items_untemplated_string.yml.md
  negative_test/playbooks/vas_prompt.yml.md
  src/schema.spec.ts
  src/update-schemas.py
Labels: enhancement

#261 Add argument-spec schema
  .config/dictionary.txt
  f/ansible-argument-specs.json
  negative_test/roles/meta/argument_specs.yml
  negative_test/roles/meta/argument_specs.yml.md
  test/roles/foo/meta/argument_specs.yml
Labels: enhancement

#262 Allow use of templated booleans for become
  .config/dictionary.txt
  f/ansible-playbook.json
  f/ansible-tasks.json
  f/ansible.json
  negative_test/playbooks/invalid_become.yml
  negative_test/playbooks/invalid_become.yml.md
  test/playbooks/tasks/templated_become.yml
  test/playbooks/templated_become.yml
  tox.ini
Labels: bug

#263 Allow environment to use jinja2 templating
  f/ansible-playbook.json
  f/ansible-tasks.json
  f/ansible.json
  negative_test/playbooks/environment.yml
  negative_test/playbooks/environment.yml.md
  test/playbooks/environment.yml
Labels: bug

#265 Bump test dependencies
  package-lock.json
  package.json
  requirements.in
  requirements.txt
Labels: skip-changelog

#266 Use json output format from check-jsonschema
  negative_test/inventory/broken_dev_inventory.yml.md
  negative_test/molecule/platforms_children/molecule.yml.md
  negative_test/molecule/platforms_networks/molecule.yml.md
  negative_test/playbooks/environment.yml.md
  negative_test/playbooks/failed_when.yml.md
  negative_test/playbooks/ignore_errors.yml.md
  negative_test/playbooks/import_playbook.yml.md
  negative_test/playbooks/invalid-failed-when.yml.md
  negative_test/playbooks/invalid-serial.yml.md
  negative_test/playbooks/invalid.yml.md
  negative_test/playbooks/invalid_become.yml.md
  negative_test/playbooks/local_action.yml.md
  negative_test/playbooks/loop.yml.md
  negative_test/playbooks/loop2.yml.md
  negative_test/playbooks/no_log_partial_template.yml.md
  negative_test/playbooks/no_log_string.yml.md
  negative_test/playbooks/roles.yml.md
  negative_test/playbooks/tags-mapping.yml.md
  negative_test/playbooks/tags-number.yml.md
  negative_test/playbooks/tasks.yml.md
  negative_test/playbooks/tasks/become_method_untemplated.yml.md
  negative_test/playbooks/tasks/ignore_errors.yml.md
  negative_test/playbooks/tasks/invalid_block.yml.md
  negative_test/playbooks/tasks/local_action.yml.md
  negative_test/playbooks/tasks/loop.yml.md
  negative_test/playbooks/tasks/loop2.yml.md
  negative_test/playbooks/tasks/no_log_number.yml.md
  negative_test/playbooks/tasks/no_log_string.yml.md
  negative_test/playbooks/tasks/tags-mapping.yml.md
  negative_test/playbooks/tasks/tags-string.yml.md
  negative_test/playbooks/tasks/with_items_boolean.yml.md
  negative_test/playbooks/tasks/with_items_untemplated_string.yml.md
  negative_test/playbooks/vars/asterisk.yml.md
  negative_test/playbooks/vars/dash-in-var-name.yml.md
  negative_test/playbooks/vars/list.yml.md
  negative_test/playbooks/vars/numeric-var-name.yml.md
  negative_test/playbooks/vars/play-keyword.yml.md
  negative_test/playbooks/vars/python-keyword.yml.md
  negative_test/playbooks/vars/varname-numeric-prefix.yml.md
  negative_test/playbooks/vas_prompt.yml.md
  negative_test/reqs3/meta/requirements.yml.md
  negative_test/roles/meta/argument_specs.yml.md
  negative_test/roles/meta/main.yml.md
  negative_test/roles/meta_invalid_collection/meta/main.yml.md
  negative_test/roles/meta_invalid_collections/meta/main.yml.md
  negative_test/roles/role_with_bad_deps_in_meta/meta/main.yml.md
  src/schema.spec.ts
Labels: skip-changelog

#267 Allow tasks files to be empty (null)
  f/ansible-playbook.json
  f/ansible-tasks.json
  f/ansible.json
  negative_test/playbooks/tasks.yml.md
  test/playbooks/tasks/empty_tasks.yml
Labels: bug

#268 Allow use of old import_playbook
  f/ansible-playbook.json
  f/ansible-tasks.json
  f/ansible.json
  negative_test/playbooks/environment.yml.md
  negative_test/playbooks/failed_when.yml.md
  negative_test/playbooks/ignore_errors.yml.md
  negative_test/playbooks/import_playbook.yml.md
  negative_test/playbooks/import_playbook_exclusive.yml
  negative_test/playbooks/import_playbook_exclusive.yml.md
  negative_test/playbooks/invalid-failed-when.yml.md
  negative_test/playbooks/invalid-serial.yml.md
  negative_test/playbooks/invalid.yml.md
  negative_test/playbooks/invalid_become.yml.md
  negative_test/playbooks/local_action.yml.md
  negative_test/playbooks/loop.yml.md
  negative_test/playbooks/loop2.yml.md
  negative_test/playbooks/no_log_partial_template.yml.md
  negative_test/playbooks/no_log_string.yml.md
  negative_test/playbooks/roles.yml.md
  negative_test/playbooks/tags-mapping.yml.md
  negative_test/playbooks/tags-number.yml.md
  negative_test/playbooks/tasks.yml.md
  negative_test/playbooks/vas_prompt.yml.md
  test/playbooks/import_playbook.yml
Labels: bug

#269 Allow check_mode and changed_when to use complex conditionals
  f/ansible-playbook.json
  f/ansible-tasks.json
  f/ansible.json
  test/playbooks/tasks/changed_when.yml
Labels: bug

#270 Allow run_once to use templated booleans
  f/ansible-playbook.json
  f/ansible-tasks.json
  f/ansible.json
  negative_test/playbooks/run_once_list.yml
  negative_test/playbooks/run_once_list.yml.md
  test/playbooks/run_once.yml
  test/playbooks/tasks/run_once.yml
Labels: bug

#271 Allow args to accept full jinja2 templates
  f/ansible-playbook.json
  f/ansible-tasks.json
  f/ansible.json
  negative_test/playbooks/tasks/args_integer.yml
  negative_test/playbooks/tasks/args_integer.yml.md
  negative_test/playbooks/tasks/args_string.yml
  negative_test/playbooks/tasks/args_string.yml.md
  test/playbooks/tasks/args.yml
Labels: bug

#272 Allow throttle to use jinja2
  f/ansible-playbook.json
  f/ansible-tasks.json
  f/ansible.json
  test/playbooks/tasks/throttled.yml
Labels: bug

#273 Allow when to use complex conditionals
  f/ansible-playbook.json
  f/ansible-tasks.json
  f/ansible.json
  negative_test/playbooks/tasks/when_integer.yml
  negative_test/playbooks/tasks/when_integer.yml.md
  negative_test/playbooks/tasks/when_object.yml
  negative_test/playbooks/tasks/when_object.yml.md
  test/playbooks/tasks/when.yml
Labels: bug

#274 Adopt standard use of $defs
  .vscode/settings.json
  README.md
  f/ansible-argument-specs.json
  f/ansible-galaxy.json
  f/ansible-inventory.json
  f/ansible-meta-runtime.json
  f/ansible-meta.json
  f/ansible-navigator.json
  f/ansible-playbook.json
  f/ansible-requirements.json
  f/ansible-tasks.json
  f/ansible.json
  f/molecule.json
  negative_test/inventory/broken_dev_inventory.yml.md
  negative_test/molecule/platforms_networks/molecule.yml.md
  negative_test/playbooks/environment.yml.md
  negative_test/playbooks/failed_when.yml.md
  negative_test/playbooks/ignore_errors.yml.md
  negative_test/playbooks/import_playbook.yml.md
  negative_test/playbooks/import_playbook_exclusive.yml.md
  negative_test/playbooks/invalid-failed-when.yml.md
  negative_test/playbooks/invalid-serial.yml.md
  negative_test/playbooks/invalid.yml.md
  negative_test/playbooks/invalid_become.yml.md
  negative_test/playbooks/local_action.yml.md
  negative_test/playbooks/loop.yml.md
  negative_test/playbooks/loop2.yml.md
  negative_test/playbooks/no_log_partial_template.yml.md
  negative_test/playbooks/no_log_string.yml.md
  negative_test/playbooks/roles.yml.md
  negative_test/playbooks/run_once_list.yml.md
  negative_test/playbooks/tags-mapping.yml.md
  negative_test/playbooks/tags-number.yml.md
  negative_test/playbooks/tasks.yml.md
  negative_test/playbooks/tasks/args_integer.yml.md
  negative_test/playbooks/tasks/args_string.yml.md
  negative_test/playbooks/tasks/become_method_untemplated.yml.md
  negative_test/playbooks/tasks/ignore_errors.yml.md
  negative_test/playbooks/tasks/no_log_number.yml.md
  negative_test/playbooks/tasks/no_log_string.yml.md
  negative_test/playbooks/tasks/when_integer.yml.md
  negative_test/playbooks/tasks/when_object.yml.md
  negative_test/playbooks/tasks/with_items_boolean.yml.md
  negative_test/playbooks/tasks/with_items_untemplated_string.yml.md
  negative_test/playbooks/vas_prompt.yml.md
  negative_test/roles/role_with_bad_deps_in_meta/meta/main.yml.md
  src/schema.spec.ts
  src/update-schemas.py
Labels: bug

#276 argspec: support seealso, sub-options, and fix choices
  .config/dictionary.txt
  f/ansible-argument-specs.json
  test/roles/foo/meta/argument_specs.yml
Labels: bug

#279 meta: make galaxy_info section optional
  f/ansible-meta.json
  test/tests/integration/rom_role/meta/main.yml
Labels: bug

#280 Remove unused definitions from subschemas
  f/ansible-playbook.json
  f/ansible-tasks.json
  src/update-schemas.py
Labels: bug

#284 f/ansible-meta.json: Add support for namespace
  .config/dictionary.txt
  f/ansible-meta.json
  negative_test/roles/meta_invalid_role_namespace/meta/main.yml
  negative_test/roles/meta_invalid_role_namespace/meta/main.yml.md
  test/roles/ns/meta/main.yml
Labels: enhancement

#283 meta: Add Mageia platform
  .config/dictionary.txt
  f/ansible-meta.json
Labels: bug

#289 Improve grammar for docs
  CONTRIBUTING.md
  README.md
Labels: enhancement

#290 Allow retries, poll and port to be templated integers
  f/ansible-playbook.json
  f/ansible-tasks.json
  f/ansible.json
  negative_test/roles/meta_invalid_role_namespace/meta/main.yml.md
  test/playbooks/tasks/templated_integers.yml
Labels: bug

#291 Fix tox deps run
  .config/dictionary.txt
  tox.ini
Labels: bug, skip-changelog

#292 Update dependencies
  package-lock.json
  package.json
  tox.ini
Labels: skip-changelog
