Repository ansible/schemas, pull requests merged in 2022-04, with the labels that each got.

#202 Make local_action allow objects
  f/ansible-playbook.json
  f/ansible-tasks.json
  negative_test/playbooks/local_action.yml
  negative_test/playbooks/tasks/local_action.yml
  test/playbooks/local_action_dict.yml
  test/playbooks/local_action_string.yml
  test/playbooks/tasks/local_action_dict.yml
  test/playbooks/tasks/local_action_string.yml
Labels: bug

#203 Add $id fields for all schemas
  f/ansible-ee.json
  f/ansible-galaxy.json
  f/ansible-inventory.json
  f/ansible-lint.json
  f/ansible-meta-runtime.json
  f/ansible-meta.json
  f/ansible-navigator.json
  f/ansible-playbook.json
  f/ansible-requirements.json
  f/ansible-vars.json
  f/molecule.json
Labels: bug

#206 Ensure block is exclusive with task model
  f/ansible-playbook.json
Labels: bug

#204 Add ability to use tasks subschema from playbook schema file (testing)
  src/schema.spec.ts
Labels: enhancement

#208 Enable cspell
  .config/dictionary.txt
  .pre-commit-config.yaml
  .prettierignore
  cspell.config.yaml
  f/ansible-navigator.json
  words.txt
Labels: bug

#210 Improve block model
  f/ansible-playbook.json
Labels: documentation

#211 Improve ansible.builtin.import_playbook
  f/ansible-playbook.json
  negative_test/playbooks/import_playbook.yml
  test/playbooks/import_playbook.yml
  test/playbooks/run.yml
Labels: bug

#212 Improve no_log
  .config/dictionary.txt
  f/ansible-playbook.json
  negative_test/playbooks/no_log_partial_template.yml
  negative_test/playbooks/no_log_string.yml
Labels: enhancement

#214 Rename TasksListModel to tasks
  f/ansible-playbook.json
  negative_test/playbooks/tasks.yml
  test/playbooks/tasks.yml
Labels: documentation

#215 Improve playbook roles
  f/ansible-playbook.json
  negative_test/playbooks/roles.yml
  test/playbooks/roles.yml
Labels: documentation

#216 Improve vars_prompt
  f/ansible-playbook.json
  negative_test/playbooks/vas_prompt.yml
  test/playbooks/run.yml
  test/playbooks/vars_prompt.yml
Labels: bug

#218 Enforced sorting of json files
  .mocharc.json
  .pre-commit-config.yaml
  .vscode/settings.json
  f/ansible-ee.json
  f/ansible-inventory.json
  f/ansible-meta-runtime.json
  f/ansible-playbook.json
  tsconfig.json
Labels: skip-changelog

#219 Enforce recursive sorting on json
  .vscode/settings.json
  f/ansible-ee.json
  f/ansible-inventory.json
  f/ansible-meta-runtime.json
  f/ansible-navigator.json
  f/ansible-playbook.json
  f/ansible-requirements.json
  f/ansible-tasks.json
  package.json
  tsconfig.json
Labels: skip-changelog

#223 gha: adopt reusable workflows
  .github/release-drafter.yml
  .github/workflows/ack.yml
  .github/workflows/push.yml
  .github/workflows/release-drafter.yml
Labels: skip-changelog

#192 molecule: add missing env property to platform
  f/molecule.json
  test/molecule/cluster/molecule.yml
Labels: bug

#224 tasks: changed_when to accept lists and strings
  f/ansible-playbook.json
  f/ansible-tasks.json
  f/ansible.json
  test/playbooks/tasks/changed_when.yml
Labels: bug

#225 with_items: require either templated or list
  f/ansible-playbook.json
  f/ansible-tasks.json
  f/ansible.json
  negative_test/playbooks/tasks/with_items_boolean.yml
  negative_test/playbooks/tasks/with_items_untemplated_string.yml
  test/playbooks/tasks/with_items.yml
Labels: bug, skip-changelog

#228 molecule: recognize platform children
  f/molecule.json
  negative_test/molecule/platforms_children/molecule.yml
  test/molecule/default/molecule.yml
Labels: bug

#229 molecule: recognize platform networks
  f/molecule.json
  negative_test/molecule/platforms_networks/molecule.yml
  test/molecule/default/molecule.yml
Labels: skip-changelog

#230 Remove unused properties from schema root
  f/ansible.json
Labels: skip-changelog

#232 Disable test of deprecated schemas
  src/schema.spec.ts
Labels: skip-changelog

#233 Allow ignore_errors to use jinja2
  f/ansible.json
  negative_test/playbooks/ignore_errors.yml
  negative_test/playbooks/tasks/ignore_errors.yml
  test/playbooks/ignore_errors..yml
  test/playbooks/tasks/ignore_errors.yml
Labels: bug

#190 Improve become_method and document implicit and explicit templating
  .config/dictionary.txt
  README.md
  f/ansible.json
  negative_test/playbooks/tasks/become_method_untemplated.yml
  test/playbooks/tasks/become_method.yml
Labels: bug, documentation

#236 tags can be either string or list of strings
  f/ansible-playbook.json
  f/ansible.json
  test/playbooks/roles.yml
  test/playbooks/tasks/tags.yml
Labels: bug

#237 Add more tests for tags
  negative_test/playbooks/tags-mapping.yml
  negative_test/playbooks/tags-number.yml
  negative_test/playbooks/tasks/tags-mapping.yml
  negative_test/playbooks/tasks/tags-string.yml
  test/playbooks/tags.yml
Labels: skip-changelog

#241 meta: require either src, name or role for each dependency entry
  f/ansible-meta.json
  negative_test/roles/role_with_bad_deps_in_meta/meta/main.yml
  test/roles/foo/meta/main.yml
Labels: bug

#242 Allow empty vars files
  f/ansible-vars.json
  negative_test/playbooks/vars/list.yml
  test/playbooks/vars/empty_vars.yml
Labels: bug

#243 Corrects example of ansible-lint config files
  f/ansible-lint.json
Labels: bug

#244 meta: allow use of collections key
  f/ansible-meta.json
  negative_test/roles/meta_invalid_collection/meta/main.yml
  negative_test/roles/meta_invalid_collections/meta/main.yml
  test/roles/foo/meta/main.yml
Labels: bug

#245 meta: configure platforms to use string versions
  f/ansible-meta.json
Labels: bug
